---
title: "Function testing"
author: "Sally Jia Hui Lim 29334330"
date: "10/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
# Mortality of first group (x): AM92 Ultimate mortality
lx <- c(10000.0000,9994.0000,9988.0636,9982.2006,9976.3909,9970.6346,9964.9313,9959.2613,9953.6144,9947.9807,9942.3402,
        9936.6730,9930.9694,9925.2094,9919.3535,9913.3821,9907.2655,9900.9645,9894.4299,9887.6126,9880.4540,9872.8954,
        9864.8688,9856.2863,9847.0510,9837.0661,9826.2060,9814.3359,9801.3123,9786.9534,9771.0789,9753.4714,9733.8865,
        9712.0728,9687.7149,9660.5021,9630.0522,9595.9715,9557.8179,9515.1040,9467.2906,9413.8004,9354.0040,9287.2164,
        9212.7143,9129.7170,9037.3973,8934.8771,8821.2612,8695.6199,8557.0118,8404.4916,8237.1329,8054.0544,7854.4508,
        7637.6208,7403.0084,7150.2401,6879.1673,6589.9258,6282.9803,5959.1680,5619.7577,5266.4604,4901.4789,4527.4960,
        4147.6708,3765.5998,3385.2479,3010.8395,2646.7416,2297.2976,1966.6499,1658.5545,1376.1906,1121.9889,897.5025,
        703.3242,539.0643,403.4023,294.2061,208.7060,143.7120,95.8476,61.7733,38.3796,22.9284,13.1359,7.1968,3.7596,
        1.8669,0.8784,0.3903,0.1632,0.0640,0.0234,0.0080,0.0025,0.0007,0.0002,0.0000,0.0000,0.0000,0.0000)
ly <- c(rep(0,3),head(lx,-3)) # Mortality of second group (y)
age_mortality <- 17:(17+length(lx)-1) # Corresponding age for mortality
```

# INSURANCE FUNCTION
```{r}
Insurance <- function(age_x1, age_y1, age_x2, age_y2, r, S, n, I, e, f, n_guaranteed, PremiumPayment, 
                      PremiumFrequency, BenefitType_x, BenefitType_y, BenefitType_joint, BenefitPayment, 
                      BenefitFrequency, Policyholder){
  
  if (Policyholder == "Group x"){ age <- age_x1 ; L <- lx ; BenefitType <- BenefitType_x
  } else if (Policyholder == "Group y"){ age <- age_y1 ; L <- ly ; BenefitType <- BenefitType_y
  } else if (Policyholder == "Joint Life"){ age_x <- age_x2 ; age_y <- age_y2 ; BenefitType <- BenefitType_joint
  } else {stop("Policyholder/age/benefittype error")}
  
  r <- r/100 ; I <- I/100 ; e <- e/100 ; f <- f/100 # Convert inputs into %
  r_12 = 12*((1+r)^(1/12)-1) # Interest rate compounding monthly
  v = 1/(1+r)
  d = 1-v
  d_12 = 12*(1-(1+r)^(-1/12)) 
  alpha_12 = r*d/(r_12*d_12)
  beta_12 = (r-r_12)/(r_12*d_12)
  delta = log(1 + r)
  
  if (Policyholder == "Joint Life"){ # FOR JOINT LIFE
    
    index_x = which(age_mortality==age_x)
    index_y = which(age_mortality==age_y)
    nExy <- function(t){
      vn = v^(n-t)
      npxy = (lx[index_x+n] / lx[index_x+t]) * (ly[index_y+n] / ly[index_y+t])
      return(vn * npxy)}
    
    Annuity <- function(age_x,age_y){
      index_x = which(age_mortality==age_x)
      index_y = which(age_mortality==age_y)
      kpx = lx[(index_x+1):(length(lx))] / lx[index_x]
      kpy = ly[(index_y+1):(length(ly))] / ly[index_y]
      N = length(age_mortality[max(index_x,index_y):length(age_mortality)])
      ax = sum( (v^(1:(N-1))) * kpx * kpy )
      return(ax) }
    
    AnnuityDue <- function(age_x,age_y){return( Annuity(age_x,age_y) + 1 )}
    
    Assurance <- function(age_x,age_y){
      if (BenefitPayment == "year end") { Ax = 1 - (r/(1+r))*(Annuity(age_x,age_y)+1)
      } else if (BenefitPayment == "immediate"){ Ax = ( 1 - (r/(1+r))*(Annuity(age_x,age_y)+1) ) * r/delta # UDD
      } else {stop("Insurance benefit payment error")}
      return(Ax)}
    
    AnnuityBenefit <- function(age_x,age_y){
      if (BenefitFrequency == "monthly"){ ax = Annuity(age_x,age_y) + 11/24 # APPROXIMATE
      } else if (BenefitFrequency == "yearly"){ ax = Annuity(age_x,age_y)
      } else {NA}
      return(ax)}
    
  } else { # FOR SINGLE LIFE: GROUP X & GROUP Y
    
    if (BenefitFrequency == "monthly"){ n_guaranteed <- n_guaranteed/12 ; Annuity_n <- (r/r_12) * ((1-v^n_guaranteed)/r)
    } else if (BenefitFrequency == "yearly"){ Annuity_n <- (1-v^n_guaranteed)/r
    } else {NA}
    
    index = which(age_mortality==age)
    npx_guaranteed <- L[index+n_guaranteed] / L[index]
    nEx <- function(t){ 
      vn = v^(n-t)
      npx = L[index+n] / L[index+t] 
      return(vn * npx)}
    
    Annuity <- function(age){ 
      index = which(age_mortality==age)
      N = length(age_mortality[index:length(age_mortality)])
      ax = sum( (v^(1:(N-1))) * L[(index+1):(length(L))] / L[index] )
      return(ax)}
    
    AnnuityDue <- function(age){return( Annuity(age) + 1 )}
    
    Assurance <- function(age){
      if (BenefitPayment == "year end") { Ax = 1 - (r/(1+r))*(Annuity(age)+1)
      } else if (BenefitPayment == "immediate"){ Ax = ( 1 - (r/(1+r))*(Annuity(age)+1) ) * (1+r)^0.5 # APPROXIMATE
      } else {stop("Insurance benefit payment error")}
      return(Ax)}
    
    AnnuityBenefit <- function(age){
      if (BenefitFrequency == "monthly"){ ax = Annuity(age) + 11/24 # APPROXIMATE
      } else if (BenefitFrequency == "yearly"){ ax = Annuity(age)
      } else {NA}
      return(ax)}
  }
  
  Benefit <- function(t){
    B <-
      if (BenefitType == "pure endowment"){ nEx(t)
      } else if (BenefitType == "term assurance"){ Assurance(age+t) - nEx(t) * Assurance(age+n)
      } else if (BenefitType == "endowment assurance"){ nEx(t) + Assurance(age+t) - nEx(t) * Assurance(age+n) 
      } else if (BenefitType == "whole life assurance"){ Assurance(age+t)
      } else if (BenefitType == "whole life annuity"){ AnnuityBenefit(age+t)
      } else if (BenefitType == "term annuity"){ AnnuityBenefit(age+t) - nEx(t) * AnnuityBenefit(age+n)
      } else if (BenefitType == "guaranteed whole life annuity"){ 
        Annuity_n + v^n_guaranteed * npx_guaranteed * AnnuityBenefit(age+n_guaranteed)
      } else if (BenefitType == "joint whole life assurance"){ Assurance(age_x,age_y) # NOT SURE
      } else if (BenefitType == "joint term life assurance"){ Annuity(age_x,age_y) # WRONG
      } else if (BenefitType == "joint whole life annuity"){ AnnuityBenefit(age_x,age_y) # NOT SURE
      } else if (BenefitType == "joint term life annuity"){ Annuity(age_x,age_y) # WRONG
      } else {stop("Insurance benefit error")}
    return(B)
  }
  
  TermAnnuityDue <- function(t){
    if (Policyholder == "Joint Life") {
      axn = AnnuityDue(age_x,age_y) - nExy(t) * AnnuityDue(age_x+n,age_y+n)
    } else { axn = AnnuityDue(age+t) - nEx(t) * AnnuityDue(age+n) }
    return(axn)
  }
  
  PremiumAnnuity <- function(t){
    ax <-
      if ((Policyholder == "Joint Life") && (PremiumPayment == "level") && (PremiumFrequency == "monthly")) {
        alpha_12*TermAnnuityDue(t) - beta_12*(1 - nExy(t)) # UDD
      } else if ((PremiumPayment == "level") && (PremiumFrequency == "monthly")){ 
        alpha_12*TermAnnuityDue(t) - beta_12*(1 - nEx(t)) # UDD
      } else if ((PremiumPayment == "level") && (PremiumFrequency == "yearly")){ TermAnnuityDue(t)
      } else if (PremiumPayment == "single"){ 1
      } else {stop("PremiumAnnuity error")}
    return(ax)
  }
  
  Premium <- S*Benefit(0)*(1+f) / (PremiumAnnuity(0) - I - e*(TermAnnuityDue(0)-1))
  
  PV_Benefit <- S*Benefit(0)
  PV_Expense <- I*Premium + e*Premium*(TermAnnuityDue(0)-1) + f*S*Benefit(0)
  PV_Premium <- Premium*PremiumAnnuity(0)
  
  # Reserve <-function(n,age, age_x, age_y, n_guaranteed, t){
  #   S*Benefit(t) - G*TermAnnuityDue(t)
  # }
  Reserve <- 12345
  # Reserve <-
  #   if ((BenefitType == "pure endowment") ||
  #       (BenefitType == "term assurance") ||
  #       (BenefitType == "endowment assurance") ||
  #       (BenefitType == "term annuity") ||
  #       (BenefitType == "guaranteed whole life annuity")){
  #     S*Benefit(0:n)*(1+f) + Premium*(I + e*(TermAnnuityDue(0:n)-1)) - Premium*PremiumAnnuity(0:n)
  # } else if ((BenefitType == "whole life assurance") ||
  #            (BenefitType == "whole life annuity")){
  #   S*Benefit(0:last(age_mortality))*(1+f) + Premium*(I + e*(TermAnnuityDue(0:last(age_mortality))-1)) # PV of future benefit + expenses
  #   - Premium*PremiumAnnuity(0:last(age_mortality))                                                    # PV of future premium
  # } else if ((BenefitType == "joint whole life assurance") || (BenefitType == "joint whole life annuity")){
  #   0
  # } else if ((BenefitType == "joint term life assurance") || (BenefitType == "joint term life annuity")){
  #   0
  # } else {stop("Reserve error")}
  
  # for(t in 0: n){
  #   if(PremiumFrequency == "yearly"){
  #     if (BenefitType == "pure endowment"){ S*v^(n-t)*p_new - G*(AnnuityDue(age+t)-v^(n-t)*p_new*AnnuityDue(age+n))
  #     } else if (BenefitType == "term assurance"){ S*(Assurance(age+t) - v^(n-t) * p_new * Assurance(age+n)) - G*(AnnuityDue(age+t)-v^(n-t)*p_new*AnnuityDue(age+n))
  #     } else if (BenefitType == "endowment assurance" ){ S*(v^(n-t) * p_new + Assurance(age+t) - v^(n-t) * p_new * Assurance(age+n)) - G*(AnnuityDue(age+t)-v^(n-t)*p_new*AnnuityDue(age+n))
  #     } else if (BenefitType == "whole life assurance"){ S*Assurance(age+t) - G*(AnnuityDue(age+t))
  #     } else if (BenefitType == "whole life annuity" ){ S*AnnuityBenefit(age+t) - G*(AnnuityDue(age+t))
  #     } else if (BenefitType == "term annuity" ){ S*(AnnuityBenefit(age+t) - v^(n-t) * p_new * AnnuityBenefit(age+n)) - G*(AnnuityDue(age+t)-v^(n-t)*p_new*AnnuityDue(age+n))
  #     } else if (BenefitType == "guaranteed whole life annuity"){ 
  #       Annuity_n + v^n_guaranteed * npx_guaranteed * AnnuityBenefit(age+n_guaranteed)
  #     } else if (BenefitType == "joint whole life assurance"){ Assurance(age_x,age_y) # NOT SURE
  #     } else if (BenefitType == "joint term life assurance" ){ Annuity(age_x,age_y) # WRONG
  #     } else if (BenefitType == "joint whole life annuity" & BenefitFrequency == "yearly"){ AnnuityBenefit(age_x,age_y) # NOT SURE
  #     } else if (BenefitType == "joint term life annuity" & BenefitFrequency == "yearly"){ Annuity(age_x,age_y) # WRONG
  #     } else {stop("Insurance benefit error")}
  #   } else if(PremiumFrequency == "monthly"){
  #   }
  # }
  
  return(list("PV Benefit"=PV_Benefit, "PV Expenses"=PV_Expense, "PV Premium"=PV_Premium, 
              "Premium"=Premium, "Reserve"=Reserve))
}
```

# TEST
```{r}
Insurance(age_x1=30, age_y1=NA, age_x2=NA, age_y2=NA, 
          r=4, S=1, n=25, I=0, e=0, f=0, n_guaranteed=NA, 
          PremiumPayment="single", PremiumFrequency="yearly", 
          BenefitType_x="endowment assurance", BenefitType_y=NA, BenefitType_joint=NA, 
          BenefitPayment="year end", BenefitFrequency="yearly", Policyholder="Group x")
```

